#!/bin/bash

# Fail2ban installation and configuration

installFail2ban() {
  echo "INFO Installing and configuring fail2ban..."

  apt --assume-yes install fail2ban

  # Read current SSH port from sshd_config — harden-ssh.sh may not have run yet
  local sshPort
  sshPort=$(grep -E "^Port " /etc/ssh/sshd_config | awk '{print $2}')
  sshPort=${sshPort:-22}

  echo "INFO Writing /etc/fail2ban/jail.local (SSH port: ${sshPort})"

  local ignoreIp="127.0.0.1/8 ::1"
  if [[ -n "${fail2banIgnoreIp:-}" ]]; then
    ignoreIp="${ignoreIp} ${fail2banIgnoreIp}"
  fi

  # Write jail.local — always overwrite for idempotent re-runs
  cat > /etc/fail2ban/jail.local <<EOF
# TYPO3 server fail2ban configuration
# Generated by install.sh — re-run installFail2ban() to update

[DEFAULT]
bantime  = 1h
findtime = 10m
maxretry = 5
backend  = auto
banaction = nftables-multiport
banaction_allports = nftables-allports
ignoreip = ${ignoreIp}

[sshd]
port     = ${sshPort}
backend  = systemd
maxretry = 3
findtime = 5m
bantime  = 24h

# port = http,https on all nginx jails: without it, custom jails fall back to the
# [DEFAULT] port list, which with the nftables banaction can cover all ports —
# a web-scanner hit would then also lock the attacker (or a false positive) out of SSH.
[nginx-http-auth]
enabled  = true
port     = http,https
maxretry = 3

[nginx-botsearch]
enabled  = true
port     = http,https
maxretry = 2
bantime  = 24h

[nginx-limit-req]
enabled  = true
port     = http,https
maxretry = 5
bantime  = 1h

[nginx-sqli-lfi]
enabled  = true
port     = http,https
filter   = nginx-sqli-lfi
maxretry = 1
bantime  = 24h
findtime = 1h
logpath  = /var/log/nginx/access.log

[nginx-4xx]
enabled  = true
port     = http,https
filter   = nginx-4xx
maxretry = 20
findtime = 5m
bantime  = 1h
logpath  = /var/log/nginx/access.log

[nginx-login-ratelimit]
enabled  = true
port     = http,https
filter   = nginx-login-ratelimit
maxretry = 3
findtime = 5m
bantime  = 6h
logpath  = /var/log/nginx/access.log

[typo3-fe-login]
enabled  = true
port     = http,https
filter   = typo3-fe-login
maxretry = 5
findtime = 10m
bantime  = 6h
logpath  = /var/log/nginx/access.log
EOF

  _writeFail2banFilters

  systemctl enable fail2ban
  systemctl restart fail2ban

  _testFail2banFilters

  echo "INFO fail2ban installed and configured"
}

_writeFail2banFilters() {
  echo "INFO Writing fail2ban custom filter files"

  # SQL injection, local file inclusion, and XSS patterns.
  # %% is required for literal % in Python ConfigParser interpolation (fail2ban).
  # NOTE: fail2ban removes the matched timestamp from the line BEFORE applying
  # failregex, so the date brackets are usually empty at match time — the
  # bracket pattern must therefore be \[[^\]]*\] (zero or more), never + .
  cat > /etc/fail2ban/filter.d/nginx-sqli-lfi.conf <<'EOF'
[Definition]
# Detect SQL injection, LFI, and XSS attempts in nginx access logs.
# The second line catches reconnaissance probes for paths that never exist on a
# TYPO3 site (WordPress logins, dotfiles, phpMyAdmin) — an immediate ban signal.
# (?i) makes matching case-insensitive (attackers vary case to evade filters).
# %% encodes a literal % sign for Python ConfigParser interpolation.
failregex = (?i)^<HOST> \S+ \S+ \[[^\]]*\] "(?:GET|POST|HEAD) [^"]*(union[\+%%20 ]+(?:all[\+%%20 ]+)?select|select[\+%%20 ]+[^"]+[\+%%20 ]+from[\+%%20 ]|insert[\+%%20 ]+into[\+%%20 ]|drop[\+%%20 ]+table[\+%%20 ]|'[\+%%20 ]*or[\+%%20 ]*'|/etc/passwd|/etc/shadow|/proc/self/|\.\.%%2[Ff]|%%2[Ee]%%2[Ee]%%2[Ff]|\.\.\/\.\.\/|<script[\s>]|javascript:|eval\(base64_decode|eval\(base64)[^"]*" \d+ \d+
            (?i)^<HOST> \S+ \S+ \[[^\]]*\] "(?:GET|POST|HEAD) [^"]*(wp-login\.php|wp-admin/|xmlrpc\.php|phpmyadmin|/\.env(?:\s|\?|\.example)|/\.git/)[^"]*" \d+ \d+

ignoreregex =
EOF

  # Repeated 4xx errors — excludes 400/401/404 and TYPO3 backend paths (see below)
  cat > /etc/fail2ban/filter.d/nginx-4xx.conf <<'EOF'
[Definition]
# Detect repeated 4xx responses. Catches scanners and probing tools.
# Excluded status codes:
#   400/404 — far too noisy (broken clients, dead links)
#   401     — the normal BasicAuth handshake: every request without credentials
#             gets a 401 first, so one page load with parallel asset requests
#             produces a burst of them. BasicAuth brute force is covered by the
#             nginx-http-auth jail (error.log) instead.
failregex = ^<HOST> \S+ \S+ \[[^\]]*\] "[^"]+" (?:40[2-35-9]|4[1-9]\d) \d+

# TYPO3 backend requests are never counted: an open backend tab with an expired
# session keeps polling via ajax and produces repeated 403s — banning the editor
# working in /typo3 is worse than missing a scanner hit on it (login brute force
# is handled by TYPO3's own lockout and optionally backend-ip-restriction.nginx).
ignoreregex = ^\S+ \S+ \S+ \[[^\]]*\] "[A-Z]+ /typo3
EOF

  # 429 Too Many Requests — triggered by nginx rate limiting (limit_req_status 429)
  cat > /etc/fail2ban/filter.d/nginx-login-ratelimit.conf <<'EOF'
[Definition]
# Detect IPs that repeatedly trigger nginx rate limiting on login paths.
# nginx returns 429 when limit_req is exceeded (see rate-limiting-zones.nginx).
failregex = ^<HOST> \S+ \S+ \[[^\]]*\] "[^"]+" 429 \d+

ignoreregex =
EOF

  # TYPO3 frontend login — repeated POST to configured login paths.
  # Only status 200 (login form shown again) and 403 count as failures.
  # A successful TYPO3 login redirects with 302/303, so users who log in
  # several times in quick succession are never counted towards a ban.
  cat > /etc/fail2ban/filter.d/typo3-fe-login.conf <<EOF
[Definition]
# Detect repeated POST requests to TYPO3 frontend login paths.
# Paths configured during installation: ${typo3LoginPathDE} (DE) and ${typo3LoginPathEN} (EN)
# Status filter: 200/403 = failed attempt, 30x redirect = successful login (not counted).
failregex = ^<HOST> \S+ \S+ \[[^\]]*\] "POST (?:${typo3LoginPathDE}|${typo3LoginPathEN})[^"]*" (?:200|403) \d+

ignoreregex =
EOF
}

_testFail2banFilters() {
  echo "INFO Testing fail2ban custom filters against synthetic attack lines..."

  # Positive-control test: every filter must match a synthetic log line it was
  # built to catch. A filter that parses cleanly but matches nothing is broken
  # (this happened once: fail2ban strips the timestamp before matching, so a
  # \[[^\]]+\] date pattern silently never matched — caught only by this test).
  local sampleLog
  sampleLog=$(mktemp)
  cat > "${sampleLog}" <<EOF
203.0.113.5 - - [10/Jul/2026:14:00:00 +0000] "GET /?id=1+UNION+SELECT+password HTTP/1.1" 200 1234
203.0.113.5 - - [10/Jul/2026:14:00:01 +0000] "GET /wp-login.php HTTP/1.1" 404 99
203.0.113.5 - - [10/Jul/2026:14:00:02 +0000] "GET /admin/secret HTTP/1.1" 403 99
203.0.113.5 - - [10/Jul/2026:14:00:03 +0000] "GET /some-page HTTP/1.1" 429 99
203.0.113.5 - - [10/Jul/2026:14:00:04 +0000] "POST ${typo3LoginPathDE} HTTP/1.1" 200 5000
EOF

  local filterName
  for filterName in nginx-sqli-lfi nginx-4xx nginx-login-ratelimit typo3-fe-login; do
    if fail2ban-regex "${sampleLog}" "/etc/fail2ban/filter.d/${filterName}.conf" 2>/dev/null \
        | grep -qE "^Lines: [0-9]+ lines, [0-9]+ ignored, [1-9][0-9]* matched"; then
      echo "INFO fail2ban filter OK: ${filterName}"
    else
      warn "fail2ban filter matched NOTHING in the positive-control test: ${filterName}"
      warn "  → check /etc/fail2ban/filter.d/${filterName}.conf — the jail is not protecting anything"
    fi
  done

  rm -f "${sampleLog}"
  return 0
}
