#!/bin/bash

# Fail2ban installation and configuration

installFail2ban() {
  echo "INFO Installing and configuring fail2ban..."

  apt --assume-yes install fail2ban

  # Read current SSH port from sshd_config — harden-ssh.sh may not have run yet
  local sshPort
  sshPort=$(grep -E "^Port " /etc/ssh/sshd_config | awk '{print $2}')
  sshPort=${sshPort:-22}

  echo "INFO Writing /etc/fail2ban/jail.local (SSH port: ${sshPort})"

  local ignoreIp="127.0.0.1/8 ::1"
  if [[ -n "${fail2banIgnoreIp:-}" ]]; then
    ignoreIp="${ignoreIp} ${fail2banIgnoreIp}"
  fi

  # Write jail.local — always overwrite for idempotent re-runs
  cat > /etc/fail2ban/jail.local <<EOF
# TYPO3 server fail2ban configuration
# Generated by install.sh — re-run installFail2ban() to update

[DEFAULT]
bantime  = 1h
findtime = 10m
maxretry = 5
backend  = auto
banaction = nftables-multiport
banaction_allports = nftables-allports
ignoreip = ${ignoreIp}

[sshd]
port     = ${sshPort}
backend  = systemd
maxretry = 3
findtime = 5m
bantime  = 24h

[nginx-http-auth]
enabled  = true
maxretry = 3

[nginx-botsearch]
enabled  = true
maxretry = 2
bantime  = 24h

[nginx-limit-req]
enabled  = true
maxretry = 5
bantime  = 1h

[nginx-sqli-lfi]
enabled  = true
filter   = nginx-sqli-lfi
maxretry = 1
bantime  = 24h
findtime = 1h
logpath  = /var/log/nginx/access.log

[nginx-4xx]
enabled  = true
filter   = nginx-4xx
maxretry = 20
findtime = 5m
bantime  = 1h
logpath  = /var/log/nginx/access.log

[nginx-login-ratelimit]
enabled  = true
filter   = nginx-login-ratelimit
maxretry = 3
findtime = 5m
bantime  = 6h
logpath  = /var/log/nginx/access.log

[typo3-fe-login]
enabled  = true
filter   = typo3-fe-login
maxretry = 5
findtime = 10m
bantime  = 6h
logpath  = /var/log/nginx/access.log
EOF

  _writeFail2banFilters

  systemctl enable fail2ban
  systemctl restart fail2ban

  _testFail2banFilters

  echo "INFO fail2ban installed and configured"
}

_writeFail2banFilters() {
  echo "INFO Writing fail2ban custom filter files"

  # SQL injection, local file inclusion, and XSS patterns.
  # %% is required for literal % in Python ConfigParser interpolation (fail2ban).
  cat > /etc/fail2ban/filter.d/nginx-sqli-lfi.conf <<'EOF'
[Definition]
# Detect SQL injection, LFI, and XSS attempts in nginx access logs.
# %% encodes a literal % sign for Python ConfigParser interpolation.
failregex = ^<HOST> \S+ \S+ \[[^\]]+\] "(?:GET|POST|HEAD) [^"]*(union[\+%%20 ]+(?:all[\+%%20 ]+)?select|select[\+%%20 ]+[^"]+[\+%%20 ]+from[\+%%20 ]|insert[\+%%20 ]+into[\+%%20 ]|drop[\+%%20 ]+table[\+%%20 ]|'[\+%%20 ]*or[\+%%20 ]*'|/etc/passwd|/etc/shadow|/proc/self/|\.\.%%2[Ff]|%%2[Ee]%%2[Ee]%%2[Ff]|\.\.\/\.\.\/|<script[\s>]|javascript:|eval\(base64_decode|eval\(base64)[^"]*" \d+ \d+

ignoreregex =
EOF

  # Repeated 4xx errors — excludes 400 (bad request) and 404 (not found) to reduce noise
  cat > /etc/fail2ban/filter.d/nginx-4xx.conf <<'EOF'
[Definition]
# Detect repeated 4xx responses, excluding 400 and 404 which are too noisy.
# Catches scanners, credential stuffers, and probing tools.
failregex = ^<HOST> \S+ \S+ \[[^\]]+\] "[^"]+" (?:40[1-35-9]|4[1-9]\d) \d+

ignoreregex =
EOF

  # 429 Too Many Requests — triggered by nginx rate limiting (limit_req_status 429)
  cat > /etc/fail2ban/filter.d/nginx-login-ratelimit.conf <<'EOF'
[Definition]
# Detect IPs that repeatedly trigger nginx rate limiting on login paths.
# nginx returns 429 when limit_req is exceeded (see rate-limiting-zones.nginx).
failregex = ^<HOST> \S+ \S+ \[[^\]]+\] "[^"]+" 429 \d+

ignoreregex =
EOF

  # TYPO3 frontend login — repeated POST to configured login paths
  cat > /etc/fail2ban/filter.d/typo3-fe-login.conf <<EOF
[Definition]
# Detect repeated POST requests to TYPO3 frontend login paths.
# Paths configured during installation: ${typo3LoginPathDE} (DE) and ${typo3LoginPathEN} (EN)
failregex = ^<HOST> \S+ \S+ \[[^\]]+\] "POST (?:${typo3LoginPathDE}|${typo3LoginPathEN})[^"]*" \d+ \d+

ignoreregex =
EOF
}

_testFail2banFilters() {
  echo "INFO Testing fail2ban custom filter syntax..."

  local logFile="/var/log/nginx/access.log"
  if [[ ! -f "${logFile}" ]]; then
    warn "nginx access log not found — skipping fail2ban-regex tests (filters will activate once nginx writes logs)"
    return 0
  fi

  local filterName
  for filterName in nginx-sqli-lfi nginx-4xx nginx-login-ratelimit typo3-fe-login; do
    if fail2ban-regex "${logFile}" "/etc/fail2ban/filter.d/${filterName}.conf" > /dev/null 2>&1; then
      echo "INFO fail2ban filter OK: ${filterName}"
    else
      warn "fail2ban filter syntax warning: ${filterName} — check /etc/fail2ban/filter.d/${filterName}.conf"
    fi
  done
}
